networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

services:
    mariadb:
        image: mariadb:10.5.8 
        environment:
            MYSQL_ROOT_PASSWORD: passpass
            MYSQL_DATABASE: dolibarr
        networks:
            - internal-pod

    web:
        image: pmoronm/dolibarr:12.0.4
        environment:
            DOLI_INSTALL_AUTO: 0
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: passpass
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'http://0.0.0.0'
            PHP_INI_DATE_TIMEZONE: 'Europe/Madrid'
        ports:
            - "81:80"
        links:
            - mariadb
        networks:
            - internal-pod
            - external-pod
